// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {audio} from '../models';
import {lrclib} from '../models';

export function DownloadLyrics(arg1:number):Promise<string>;

export function FlagLyrics(arg1:number,arg2:string):Promise<void>;

export function GetAlbum(arg1:number):Promise<database.PersistentAlbum>;

export function GetAlbums():Promise<Array<database.PersistentAlbum>>;

export function GetArtist(arg1:number):Promise<database.PersistentArtist>;

export function GetArtists():Promise<Array<database.PersistentArtist>>;

export function GetConfig():Promise<database.PersistentConfig>;

export function GetDirectories():Promise<Array<string>>;

export function GetInit():Promise<boolean>;

export function GetPlayerState():Promise<audio.PlayerState>;

export function GetTrack(arg1:number):Promise<database.PersistentTrack>;

export function GetTracks():Promise<Array<database.PersistentTrack>>;

export function GetTracksByAlbum(arg1:number):Promise<Array<database.PersistentTrack>>;

export function GetTracksByArtist(arg1:number):Promise<Array<database.PersistentTrack>>;

export function InitializeLibrary():Promise<void>;

export function PauseTrack():Promise<void>;

export function PlayTrack(arg1:number):Promise<void>;

export function PublishLyrics(arg1:string,arg2:string,arg3:string,arg4:number,arg5:any,arg6:any,arg7:boolean):Promise<lrclib.PublishResponse>;

export function ResumeTrack():Promise<void>;

export function SearchLyrics(arg1:string,arg2:string,arg3:string,arg4:string):Promise<lrclib.SearchResponse>;

export function SeekTrack(arg1:number):Promise<void>;

export function SetDirectories(arg1:Array<string>):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function StopTrack():Promise<void>;

export function UpdateConfig(arg1:database.PersistentConfig):Promise<void>;
