// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrack(arg1) {
  return window['go']['app']['App']['AddTrack'](arg1);
}

export function DownloadLyrics(arg1) {
  return window['go']['app']['App']['DownloadLyrics'](arg1);
}

export function FlagLyrics(arg1, arg2) {
  return window['go']['app']['App']['FlagLyrics'](arg1, arg2);
}

export function GetAlbum(arg1) {
  return window['go']['app']['App']['GetAlbum'](arg1);
}

export function GetAlbums() {
  return window['go']['app']['App']['GetAlbums']();
}

export function GetArtist(arg1) {
  return window['go']['app']['App']['GetArtist'](arg1);
}

export function GetArtists() {
  return window['go']['app']['App']['GetArtists']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetDirectories() {
  return window['go']['app']['App']['GetDirectories']();
}

export function GetInit() {
  return window['go']['app']['App']['GetInit']();
}

export function GetPlayerState() {
  return window['go']['app']['App']['GetPlayerState']();
}

export function GetTrack(arg1) {
  return window['go']['app']['App']['GetTrack'](arg1);
}

export function GetTracks() {
  return window['go']['app']['App']['GetTracks']();
}

export function GetTracksByAlbum(arg1) {
  return window['go']['app']['App']['GetTracksByAlbum'](arg1);
}

export function GetTracksByArtist(arg1) {
  return window['go']['app']['App']['GetTracksByArtist'](arg1);
}

export function InitializeLibrary() {
  return window['go']['app']['App']['InitializeLibrary']();
}

export function PauseTrack() {
  return window['go']['app']['App']['PauseTrack']();
}

export function PlayTrack(arg1) {
  return window['go']['app']['App']['PlayTrack'](arg1);
}

export function PublishLyrics(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['PublishLyrics'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ResumeTrack() {
  return window['go']['app']['App']['ResumeTrack']();
}

export function SearchLyrics(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SearchLyrics'](arg1, arg2, arg3, arg4);
}

export function SeekTrack(arg1) {
  return window['go']['app']['App']['SeekTrack'](arg1);
}

export function SetDirectories(arg1) {
  return window['go']['app']['App']['SetDirectories'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['app']['App']['SetVolume'](arg1);
}

export function StopTrack() {
  return window['go']['app']['App']['StopTrack']();
}

export function UpdateConfig(arg1) {
  return window['go']['app']['App']['UpdateConfig'](arg1);
}
