name: Test Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install system dependencies (Ubuntu/Linux)
        if: runner.os == 'Linux'
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y software-properties-common ca-certificates apt-transport-https || true
          sudo add-apt-repository universe || true
          sudo apt-get update

          pkgs=(pkg-config libgtk-3-dev libgirepository1.0-dev libcairo2-dev libjson-glib-dev libatk1.0-dev libpango1.0-dev gcc g++)

          for candidate in libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libwebkit2gtk-dev; do
            if apt-cache show "$candidate" >/dev/null 2>&1; then
              pkgs+=("$candidate")
              echo "Installing detected webkit package: $candidate"
              break
            fi
          done

          echo "Installing packages: ${pkgs[*]}"
          sudo apt-get install -y "${pkgs[@]}"
          sudo apt-get clean

      - name: Test build for current platform
        run: |
          wails build -clean
          ls -la build/bin/

      - name: Test cross-platform builds
        run: |
          mkdir -p test-builds
          wails build -platform linux/amd64 -clean -o test-builds/lrcget-linux-amd64
          wails build -platform windows/amd64 -clean -o test-builds/lrcget-windows-amd64.exe
          ls -la test-builds/
          file test-builds/*
